version: "3"
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - GREETINGS=Hello Rubiko Tech!
    networks:
      mynetwork:
        aliases:
          - web
  curl:
    depends_on:
      - web
    image: curlimages/curl
    command: ["curl", "http://web:5000/health"]
    networks:
      - mynetwork
networks:
  mynetwork:
    external: false
    name: mynetwork
